# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      args: [--config, .flake8]

- repo: https://github.com/gitguardian/ggshield
  rev: v1.10.5
  hooks:
    - id: ggshield
      language_version: python3
      stages: [commit]
