# Generated by Django 3.2.4 on 2021-06-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('BR', 'Battle Royale'), ('CO', 'Cooperation'), ('CH', 'Championship')], default='BR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('picture', models.ImageField(upload_to='uploads/')),
                ('player_code', models.CharField(blank=True, max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='treffen.game')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affected_players', to='treffen.mission')),
                ('ziel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jaeger', to='treffen.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='mission_set',
            field=models.ManyToManyField(related_name='affected_games', to='treffen.Mission'),
        ),
    ]
