# Generated by Django 3.2.4 on 2021-06-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
