# Generated by Django 3.2.4 on 2021-06-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0003_alter_player_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting to start'), ('S', 'Started'), ('P', 'PAUSED'), ('O', 'OVER')], default='W', max_length=2),
        ),
    ]
