# Generated by Django 3.2.4 on 2021-06-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0005_auto_20210618_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting'), ('S', 'Is playing'), ('IO', 'Is out')], default='W', max_length=20),
        ),
    ]
